- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled

- name: Allow incoming traffic on port 3306 for TCP
  community.general.ufw:
    rule: allow
    port: 3306
    proto: tcp
    comment: "Allow port for MySQL"
